<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */


/**
 * Implements hook_cron().
 *
 */
function islandora_readership_reporter_cron() {
  $now = time();
  $day = (int) date('d', $now);

  // Run on the first of each month
  $run_date = 20;
  if ($day == $run_date) {
    module_load_include('inc', 'islandora_readership_reporter', 'includes/utilities');
    islandora_readership_reporter_run_readership_reports();
  }
}

/**
 * Implements hook_mail().
 *
 */
function islandora_readership_reporter_mail($key, &$message, $params) {
  switch($key) {
    case 'report':
  }
}
